version: '3.8'

services:
  db:
    build: ./database
    container_name: sisyphus_db
    volumes:
      - sisyphus_prod_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    expose:
      - '5433'
    ports:
      - '5433:5433'
    command: -p 5433

  api:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: sisyphus_api
    volumes:
      - static_volume:/home/sisyphus/app/frontend/static
    expose:
      - 8001
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - api
    volumes:
      - static_volume:/home/sisyphus/app/static


volumes:
  sisyphus_prod_data:
  static_volume:
