version: '3.8'

services:
  db_prod:
    build: ./database
    container_name: sisyphus_db_prod
    volumes:
      - ./database/shared:/shared/
      - sisyphus_prod_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    expose:
      - '5433'
    restart: always
    ports:
      - '5433:5433'
    command: -p 5433

  jobs_prod:
    build: ./background_jobs
    container_name: sisyphus_jobs_prod
    volumes:
      - ./background_jobs/shared/:/shared/
      - sisyphus_media_prod:/export
    env_file:
      - ./.env.prod
    restart: always

  api_prod:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: sisyphus_api_prod
    volumes:
      - ./app/:/home/sisyphus/app
      - sisyphus_static_prod:/home/sisyphus/app/frontend/static
      - sisyphus_media_prod:/home/sisyphus/app/media
    expose:
      - 8001
    restart: always
    env_file:
      - ./.env.prod
    depends_on:
      - db_prod

  nginx_prod:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: sisyhus_server_prod
    ports:
      - 1337:80
    restart: always
    depends_on:
      - api_prod
    volumes:
      - sisyphus_static_prod:/home/sisyphus/app/static
      - sisyphus_media_prod:/home/sisyphus/app/media


volumes:
  sisyphus_prod_data:
  sisyphus_static_prod:
  sisyphus_media_prod:
