version: '3.8'

services:
  db_test:
    build: ./database
    container_name: sisyphus_db_test
    volumes:
      - sisyphus_test_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.test
    expose:
      - '5434'
    restart: always
    ports:
      - '5434:5434'
    command: -p 5434

  api_test:
    build:
      context: ./app
      dockerfile: Dockerfile.test
    container_name: sisyphus_api_test
    volumes:
      - sisyphus_static_test:/home/sisyphus/app/frontend/static
    expose:
      - 8001
    restart: always
    env_file:
      - ./.env.test
    depends_on:
      - db_test

  nginx_test:
    container_name: sisyphus_server_test
    build:
      context: ./nginx
      dockerfile: Dockerfile.test
    ports:
      - 1338:80
    restart: always
    depends_on:
      - api_test
    volumes:
      - sisyphus_static_test:/home/sisyphus/app/static


volumes:
  sisyphus_test_data:
  sisyphus_static_test:
