version: '3.8'

services:
  db:
    build: ./database
    container_name: sisyphus_db_test
    volumes:
      - ./database/shared:/shared/
      - sisyphus_test_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.test
    expose:
      - '5434'
    restart: always
    ports:
      - '5434:5434'
    command: -p 5434

  jobs:
    build: ./background_jobs
    container_name: sisyphus_jobs_test
    volumes:
      - ./background_jobs/shared/:/shared/
    env_file:
      - ./.env.test
    restart: always

  api:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    container_name: sisyphus_api_test
    volumes:
      - ./app/:/home/sisyphus/app
      - sisyphus_static_test:/home/sisyphus/app/frontend/static
    expose:
      - 8001
    restart: always
    env_file:
      - ./.env.test
    depends_on:
      - db

  nginx:
    container_name: sisyphus_server_test
    build: ./nginx
    ports:
      - 1338:80
    restart: always
    depends_on:
      - api
    volumes:
      - sisyphus_static_test:/home/sisyphus/app/static


volumes:
  sisyphus_test_data:
  sisyphus_static_test:
