version: '3.8'

services:
  db:
    build: ./database
    container_name: sisyphus_db
    volumes:
      - sisyphus_dev_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    expose:
      - '5433'
    restart: always
    ports:
      - '5433:5433'
    command: -p 5433


  api:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: sisyphus_api
    volumes:
      - ./app/:/home/sisyphus/app
      - /tmp:/home/sisyphus/app/frontend/static/tmp
    restart: always
    ports:
      - 8002:8002
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  sisyphus_dev_data: