

# pull official base image
FROM python:3.11-bullseye


# set work directory
WORKDIR /home/sisyphus/app

RUN mkdir /home/sisyphus/app/frontend/static/tmp/


# install psycopg2 dependencies
RUN apt-get update
RUN apt-get install -y postgresql gcc musl netcat


COPY . .
# install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ./entrypoint.dev.sh /entrypoint.dev.sh
RUN chmod +x /entrypoint.dev.sh



CMD ["sh", "./entrypoint.dev.sh"]
