# Generated by Django 4.2.5 on 2023-09-15 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAbsenceCodes',
            fields=[
                ('id_asset_absence_code', models.AutoField(primary_key=True, serialize=False)),
                ('asset_absence_code', models.CharField()),
                ('asset_absence_code_abbreviation', models.CharField()),
            ],
            options={
                'db_table': 'asset_absence_codes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id_asset', models.AutoField(primary_key=True, serialize=False)),
                ('asset_description', models.CharField()),
                ('asset_internal_alias', models.CharField()),
                ('year_of_production', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssetTypes',
            fields=[
                ('id_asset_type', models.AutoField(primary_key=True, serialize=False)),
                ('asset_type', models.CharField()),

            ],
            options={
                'db_table': 'asset_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField()),
                ('company_street', models.CharField()),
                ('company_zipcode', models.CharField()),
                ('company_country', models.CharField()),
                ('company_city', models.CharField()),
                ('company_internal_alias', models.CharField(unique=True)),
                ('company_email', models.CharField(blank=True, null=True)),
                ('is_customer', models.BooleanField(blank=True, null=True)),
                ('is_supplier', models.BooleanField(blank=True, null=True)),
                ('is_subcontractor', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id_currency', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField()),
                ('currency_abbreviation', models.CharField()),
                ('currency_account_nr', models.CharField()),
            ],
            options={
                'db_table': 'currencies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAbsenceCodes',
            fields=[
                ('id_employee_absence_code', models.AutoField(primary_key=True, serialize=False)),
                ('employee_absence_code', models.CharField()),
                ('employee_absence_code_abbreviation', models.CharField()),
            ],
            options={
                'db_table': 'employee_absence_codes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField()),
                ('employee_last_name', models.CharField()),
                ('employee_street', models.CharField()),
                ('employee_zipcode', models.CharField()),
                ('employee_city', models.CharField()),
                ('employee_email', models.CharField()),
                ('employee_cell_phone', models.CharField()),
                ('employee_birthday', models.DateField()),
                ('employee_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('employee_fte', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('employee_internal_alias', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTypes',
            fields=[
                ('id_employee_type', models.AutoField(primary_key=True, serialize=False)),
                ('employee_type_description', models.CharField()),
            ],
            options={
                'db_table': 'employee_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_text', models.CharField()),
            ],
            options={
                'db_table': 'invoices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvoiceStates',
            fields=[
                ('id_invoice_state', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_state', models.CharField()),
            ],
            options={
                'db_table': 'invoice_states',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvoiceTerms',
            fields=[
                ('id_invoice_term', models.AutoField(primary_key=True, serialize=False)),
                ('due_days', models.IntegerField(unique=True)),
                ('term_title', models.CharField()),
            ],
            options={
                'db_table': 'invoice_terms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField()),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('fk_customer', models.ForeignKey(db_column='fk_customer', on_delete=django.db.models.deletion.DO_NOTHING, to='api.companies')),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesState',
            fields=[
                ('id_sales_state', models.AutoField(primary_key=True, serialize=False)),
                ('sales_state', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'sales_state',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SysRecStates',
            fields=[
                ('id_sys_rec_status', models.AutoField(primary_key=True, serialize=False)),
                ('sys_rec_status', models.CharField()),
                ('entity', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_rec_states',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskStates',
            fields=[
                ('id_task_state', models.AutoField(primary_key=True, serialize=False)),
                ('task_state', models.CharField()),
            ],
            options={
                'db_table': 'task_states',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id_unit', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField()),
                ('unit_abbreviation', models.CharField()),
            ],
            options={
                'db_table': 'units',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id_vat', models.AutoField(primary_key=True, serialize=False)),
                ('vat', models.DecimalField(decimal_places=3, max_digits=3, unique=True)),
                ('vat_title', models.CharField()),
            ],
            options={
                'db_table': 'vat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaskTemplates',
            fields=[
                ('id_task_template', models.AutoField(primary_key=True, serialize=False)),
                ('fk_project', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('task_description', models.CharField()),
                ('fk_currency', models.ForeignKey(blank=True, db_column='fk_currency', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.currencies')),
                ('fk_unit', models.ForeignKey(db_column='fk_unit', on_delete=django.db.models.deletion.DO_NOTHING, to='api.units')),
                ('fk_vat', models.ForeignKey(blank=True, db_column='fk_vat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.vat')),
            ],
            options={
                'db_table': 'task_templates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('task_date_from', models.DateField(blank=True, null=True)),
                ('task_date_to', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('task_description', models.CharField()),
                ('internal_info', models.CharField(blank=True, null=True)),
                ('customer_reference', models.CharField(blank=True, null=True)),
                ('fk_subcontractor', models.IntegerField(blank=True, null=True)),
                ('task_time_from', models.TimeField(blank=True, null=True)),
                ('task_time_to', models.TimeField(blank=True, null=True)),
                ('fk_asset_1', models.ForeignKey(blank=True, db_column='fk_asset_1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.assets')),
                ('fk_asset_2', models.ForeignKey(blank=True, db_column='fk_asset_2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_fk_asset_2_set', to='api.assets')),
                ('fk_currency', models.ForeignKey(blank=True, db_column='fk_currency', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.currencies')),
                ('fk_employee_1', models.ForeignKey(blank=True, db_column='fk_employee_1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.employees')),
                ('fk_employee_2', models.ForeignKey(blank=True, db_column='fk_employee_2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_fk_employee_2_set', to='api.employees')),
                ('fk_invoice', models.ForeignKey(blank=True, db_column='fk_invoice', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.invoices')),
                ('fk_project', models.ForeignKey(db_column='fk_project', on_delete=django.db.models.deletion.DO_NOTHING, to='api.projects')),
                ('fk_task_state', models.ForeignKey(db_column='fk_task_state', on_delete=django.db.models.deletion.DO_NOTHING, to='api.taskstates')),
                ('fk_unit', models.ForeignKey(blank=True, db_column='fk_unit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.units')),
                ('fk_vat', models.ForeignKey(blank=True, db_column='fk_vat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.vat')),
            ],
            options={
                'db_table': 'tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('sale_unit_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('sale_reference', models.CharField()),
                ('sale_description', models.CharField(blank=True, null=True)),
                ('sale_time', models.TimeField(blank=True, null=True)),
                ('fk_currency', models.ForeignKey(blank=True, db_column='fk_currency', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.currencies')),
                ('fk_invoice', models.ForeignKey(blank=True, db_column='fk_invoice', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.invoices')),
                ('fk_project', models.ForeignKey(db_column='fk_project', on_delete=django.db.models.deletion.DO_NOTHING, to='api.projects')),
                ('fk_sales_status', models.ForeignKey(blank=True, db_column='fk_sales_status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.salesstate')),
                ('fk_unit', models.ForeignKey(db_column='fk_unit', on_delete=django.db.models.deletion.DO_NOTHING, to='api.units')),
                ('fk_vat', models.ForeignKey(blank=True, db_column='fk_vat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.vat')),
            ],
            options={
                'db_table': 'sales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvoiceTexts',
            fields=[
                ('id_invoice_text', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_text', models.CharField()),
                ('fk_customer', models.ForeignKey(db_column='fk_customer', on_delete=django.db.models.deletion.DO_NOTHING, to='api.companies')),
            ],
            options={
                'db_table': 'invoice_texts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='invoices',
            name='fk_invoice_state',
            field=models.ForeignKey(db_column='fk_invoice_state', on_delete=django.db.models.deletion.DO_NOTHING, to='api.invoicestates'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='fk_invoice_terms',
            field=models.ForeignKey(db_column='fk_invoice_terms', on_delete=django.db.models.deletion.DO_NOTHING, to='api.invoiceterms'),
        ),
        migrations.AddField(
            model_name='employees',
            name='fk_employee_type',
            field=models.ForeignKey(db_column='fk_employee_type', on_delete=django.db.models.deletion.DO_NOTHING, to='api.employeetypes'),
        ),
        migrations.AddField(
            model_name='employees',
            name='fk_sys_rec_status',
            field=models.ForeignKey(db_column='fk_sys_rec_status', on_delete=django.db.models.deletion.DO_NOTHING, to='api.sysrecstates'),
        ),
        migrations.CreateModel(
            name='EmployeeAbsences',
            fields=[
                ('id_employee_absence', models.AutoField(primary_key=True, serialize=False)),
                ('employee_absence_from', models.DateTimeField()),
                ('employee_absence_to', models.DateTimeField()),
                ('fk_employee', models.ForeignKey(db_column='fk_employee', on_delete=django.db.models.deletion.DO_NOTHING, to='api.employees')),
                ('fk_employee_absence_code', models.ForeignKey(db_column='fk_employee_absence_code', on_delete=django.db.models.deletion.DO_NOTHING, to='api.employeeabsencecodes')),
            ],
            options={
                'db_table': 'employee_absences',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='companies',
            name='fk_sys_rec_status',
            field=models.ForeignKey(db_column='fk_sys_rec_status', on_delete=django.db.models.deletion.DO_NOTHING, to='api.sysrecstates'),
        ),
        migrations.AddField(
            model_name='assets',
            name='fk_asset_type',
            field=models.ForeignKey(db_column='fk_asset_type', on_delete=django.db.models.deletion.DO_NOTHING, to='api.assettypes'),
        ),
        migrations.AddField(
            model_name='assets',
            name='fk_sys_rec_status',
            field=models.ForeignKey(db_column='fk_sys_rec_status', on_delete=django.db.models.deletion.DO_NOTHING, to='api.sysrecstates'),
        ),
        migrations.CreateModel(
            name='AssetAbsences',
            fields=[
                ('id_asset_absence', models.AutoField(primary_key=True, serialize=False)),
                ('asset_absence_from', models.DateTimeField()),
                ('asset_absence_to', models.DateTimeField()),
                ('fk_asset', models.ForeignKey(db_column='fk_asset', on_delete=django.db.models.deletion.DO_NOTHING, to='api.assets')),
                ('fk_asset_absence_code', models.ForeignKey(db_column='fk_asset_absence_code', on_delete=django.db.models.deletion.DO_NOTHING, to='api.assetabsencecodes')),
            ],
            options={
                'db_table': 'asset_absences',
                'managed': True,
            },
        ),
    ]
